{% set python_min = "3.11" %}
{% set name = "hats" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats/archive/v{{ version }}.tar.gz
  sha256: 50bfa0be33c9c4aa18ea42fb500ca0c573331478e375cd8e8e80e76a53dba9ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.8.0
    - astropy-base >=6.1.5
    - cdshealpix >=0.8.0
    - fsspec >=2023.10.0
    - jproperties >=2.0.0
    - mocpy >=0.19.0
    - nested-pandas >=0.6.7,<0.7.0
    - numba >=0.58
    - numpy >=2,<3
    - pandas >=2.0
    - pyarrow >=14.0.1,!=19.0.0
    - pydantic >=2.0
    - scipy >=1.7.2
    - typing-extensions >=4.3.0
    - universal_pathlib >=0.3.1

test:
  imports:
    - hats
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-timeout
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/hats
  summary: 'A HATS astronomical catalog format reader library'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smcguire-cmu
    - olivialynn
    - gitosaurus
    - dougbrn
    - hombit
    - astronomy-commons/lincc-frameworks
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
