{% set python_min = "3.10" %}
{% set name = "hats" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats/archive/v{{ version }}.tar.gz
  sha256: 7fc21a5699ea42b3877601290be1e0a827aa27fc7e2aafe29bbbec90805a89a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.8.0
    - astropy-base >=6.1.5
    - cdshealpix >=0.7.0
    - fsspec >=2023.10.0
    - jproperties >=2.0.0
    - matplotlib-base >=3.10.1
    - mocpy >=0.17.1
    - nested-pandas >=0.4.1
    - numba >=0.58
    - numpy <3
    - pandas >=2.0
    - pyarrow >=14.0.1
    - pydantic >=2.0
    - scipy >=1.7.2
    - typing-extensions >=4.3.0
    - universal_pathlib >=0.2.2

test:
  imports:
    - hats
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-timeout
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/hats
  summary: 'A HATS astronomical catalog format reader library'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
