{% set name = "hats" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats/archive/v{{ version }}.tar.gz
  sha256: 899992133645df7d849ae36c7f34c9e78572dac5032c2c76e7e7f0e1492ec667

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - aiohttp
    - astropy <6.1
    - fsspec >=2023.10.0
    - healpy
    - jproperties
    - matplotlib-base >=3.3,<3.9
    - mocpy
    - numba >=0.58
    - numpy <3
    - pandas
    - pyarrow >=14.0.1
    - pydantic
    - typing-extensions >=4.3.0
    - universal_pathlib

test:
  imports:
    - hats
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-timeout
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/hats
  summary: 'A HATS astronomical catalog format reader library'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
