{% set python_min = "3.10" %}
{% set name = "hats" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats/archive/v{{ version }}.tar.gz
  sha256: 1de23ea616faf9f2797df1b52fc9512a5744ce56d00bc7c5196905b062e16002

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - astropy-base <6.1
    - fsspec >=2023.10.0
    - jproperties
    - matplotlib-base >=3.3,<3.9
    - mocpy >=0.17.1
    - numba >=0.58
    - numpy <3
    - pandas
    - pyarrow >=14.0.1
    - pydantic
    - scipy
    - typing-extensions >=4.3.0
    - universal_pathlib

test:
  imports:
    - hats
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-timeout
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/hats
  summary: 'A HATS astronomical catalog format reader library'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
